#!/bin/bash

# URL for Pikachu's data
URL="https://pokeapi.co/api/v2/pokemon/pikachu"

# Output files
DATA_FILE="data.json"
ERROR_FILE="errors.txt"

# Make the API request
curl -s -f "$URL" -o "$DATA_FILE"

# Check if the curl command succeeded
if [ $? -ne 0 ]; then
    echo "[$(date)] Failed to retrieve data from $URL" >> "$ERROR_FILE"
fi
